---
- hosts: all
  tasks:
    # TODO: Add mysql dump backup step
    - name: Update code in project directory
      git:
        repo: "{{ git_repo }}"
        dest: "{{ project_dir }}"

    - name: Ensure containers are running and restarted
      docker_service:
        state: present
        project_src: "{{ project_dir }}"
        restarted: yes
        files:
          - "docker/docker-compose.yml"

    - name: Run composer install
      command: "docker exec docker_php_1 composer install -o"

    - name: Clear cache in php container
      command: "docker exec docker_php_1 bin/console cache:clear --env=prod --no-debug"

    - name: Clearing doctrine cache for metadata
      command: "docker exec docker_php_1 bin/console --no-interaction doctrine:cache:clear-metadata"

    - name: Clearing doctrine cache for queries
      command: "docker exec docker_php_1 bin/console --no-interaction doctrine:cache:clear-query"

    - name: Apply migrations in php container
      command: "docker exec docker_php_1 bin/console doctrine:migrations:migrate -n"

    - name: Warmup cache in php container
      command: "docker exec docker_php_1 bin/console cache:warmup --env=prod -no-debug"
