---
- hosts: all
  tasks:
    - name: Ensure Docker, python pip and Docker-Compose are installed
      apt:
        update_cache: true
        name:
          - docker=1.5-1build1
          - docker-compose=1.17.1-2
          - python-pip=9.0.1-2.3~ubuntu1
    - name: Ensure python packages are installed
      pip:
        name:
          - docker=3.7.0
          - docker-compose=1.23.2
          - docker-pycreds=0.4.0
          - dockerpty=0.4.1
    - name: Ensure runuser exists
      user:
        group: "{{ default_group }}"
        name: "{{ default_user }}"
        system: true
        uid: 9000
        comment: User to run the system with

    - name: Ensure project directory exists
      file:
        state: directory
        path: "{{ project_dir }}"
        user: "{{ default_user }}"
        group: "{{ default_group }}"
        recurse: true

