---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  tasks:
    - name: Make sure python 2 is installed
      raw: sudo apt-get -y install python

- hosts: all
  tasks:
    - name: Ensure Docker, python pip and Docker-Compose are installed
      apt:
        update_cache: true
        name:
          - docker
          - docker-compose
          - python-pip

    - name: Ensure python packages are installed
      pip:
        name:
          - docker==3.7.0
          - docker-compose==1.23.2
          - docker-pycreds==0.4.0
          - dockerpty==0.4.1
    - name: Ensure rungroup exists
      group:
        name: "{{ default_group }}"
        state: present
        system: yes

    - name: Ensure runuser exists
      user:
        group: "{{ default_group }}"
        name: "{{ default_user }}"
        groups:
          - docker
        system: true
        uid: 9000
        comment: User to run the system with

    - name: Ensure project directory exists
      file:
        state: directory
        path: "{{ project_dir }}"
        owner: "{{ default_user }}"
        group: "{{ default_group }}"
        recurse: true

