---
- hosts: all
  vars:
    project_dir: /srv/todoapp
  tasks:
    - name: Ensure Docker and Docker-Compose are installed
      apt:
        update: true
        name:
          - docker=1.5-1build1
          - docker-compose=1.17.1-2
          - python-pip
    - name: Ensure runuser exists
      user:
        group: rungroup
        name: runuser
        system: true
        uid: 9000
        comment: User to run the system with

    - name: Ensure project directory exists
      file:
        state: directory
        path: "{{ project_dir }}"
        user: runuser
        group: rungroup
        recurse: true

    - name: Update code in project directory
      git:
        repo: https://github.com/survivorbat/Simple-Symfony-App.git
        dest: "{{ project_dir }}"
        owner: runuser
        group: rungroup